### ISSUE TITLE
Applications that use this plugin has stopped on start

### ISSUE THREAD

**Issue by marcbuils** [NativeScript/nativescript-fresco#13]
Hi,

I reproduce the problem on my application and the Fresco Sample.
On Android (tested on the android SDK simulator with a nexus 5 configuration).

When the application start
Then I see the following system error "Unfortunately, {N} Fresco sample has stopped"

TNS Info for Fresco Sample :

```
MacBook-Pro-de-Marc:frescoSample marcbuils$ tns info
All NativeScript components versions information
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.2.1           │ 2.2.1          │ Up to date       │
│ tns-core-modules │ 2.2.0           │ 2.2.1          │ Update available │
│ tns-android      │ 2.2.0           │ 2.2.0          │ Up to date       │
│ tns-ios          │                 │ 2.2.1          │ Not installed    │
```

TNS info for a custom test app :

```
MacBook-Pro-de-Marc:demo marcbuils$ tns info
All NativeScript components versions information
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.2.1           │ 2.2.1          │ Up to date    │
│ tns-core-modules │ 2.2.1           │ 2.2.1          │ Up to date    │
│ tns-android      │ 2.2.0           │ 2.2.0          │ Up to date    │
│ tns-ios          │                 │ 2.2.1          │ Not installed │
```

Best Regards,
Marc

**Comment by marcbuils** [comment]
In fact, I have this problem when I add the following lines in app.gradle :
dependencies {
    compile "com.facebook.fresco:fresco:0.9.0+"
}

Only on a simulator with a x86_64 CPU because libNativescript.so isn't present in lib/x86_64 directory inner the apk.

So, it's not a bug of this plugin.

For information, logs for "adb logcat":

```
08-18 22:13:16.870  1520  1531 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.nativescript.demo/com.tns.NativeScriptActivity (has extras)} from uid 10007 on display 0
08-18 22:13:16.903  2779  2779 I art     : Not late-enabling -Xcheck:jni (already on)
08-18 22:13:16.908  1520  1796 I ActivityManager: Start proc 2779:org.nativescript.demo/u0a194 for activity org.nativescript.demo/com.tns.NativeScriptActivity
08-18 22:13:17.047  2779  2779 D AndroidRuntime: Shutting down VM
08-18 22:13:17.054  2779  2779 E AndroidRuntime: FATAL EXCEPTION: main
08-18 22:13:17.054  2779  2779 E AndroidRuntime: Process: org.nativescript.demo, PID: 2779
08-18 22:13:17.054  2779  2779 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.nativescript.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.demo-1/lib/x86_64, /data/app/org.nativescript.demo-1/base.apk!/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libNativeScript.so"
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at java.lang.Runtime.loadLibrary(Runtime.java:367)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at java.lang.System.loadLibrary(System.java:1076)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:43)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:15)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at android.app.ActivityThread.-wrap1(ActivityThread.java)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5417)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-18 22:13:17.054  2779  2779 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-18 22:13:17.056  1520  1884 W ActivityManager:   Force finishing activity org.nativescript.demo/com.tns.NativeScriptActivity
08-18 22:13:17.359  1520  1884 I WindowManager: Screenshot max retries 4 of Token{a7bc826 ActivityRecord{77e7f81 u0 org.nativescript.demo/com.tns.NativeScriptActivity t9 f}} appWin=Window{6da9db9 u0 Starting org.nativescript.demo} drawState=1
08-18 22:13:17.360  1520  1520 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 294ms
08-18 22:13:17.440  1520  2432 I OpenGLRenderer: Initialized EGL, version 1.4
08-18 22:13:17.497  1520  1539 I Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
08-18 22:13:17.861  1520  1534 W ActivityManager: Activity pause timeout for ActivityRecord{77e7f81 u0 org.nativescript.demo/com.tns.NativeScriptActivity t9 f}
08-18 22:13:27.897  1520  1534 W ActivityManager: Activity destroy timeout for ActivityRecord{77e7f81 u0 org.nativescript.demo/com.tns.NativeScriptActivity t9 f}
08-18 22:14:46.369  1520  1533 I UsageStatsService: User[0] Flushing usage stats to disk
08-18 22:18:17.362  2779  2779 I Process : Sending signal. PID: 2779 SIG: 9
```

**Comment by WouterVanVegchel** [comment]
Has this been solved by nativescript?

**Comment by pboulch** [comment]
Has this been solved by nativescript?

**Comment by VladimirAmiorkov** [comment]
Hi @WouterVanVegchel ,

This issue has been closed by the person who opened it after explanation of the cause of the error. Also it is worth mentioning that this plugin is no longer being developer and is deprecated in favor of [nativescript-image](https://market.nativescript.org/plugins/nativescript-image)
