### ISSUE TITLE
onHiddenChanged failed

### ISSUE THREAD

**Issue by AntonioCuevaUrraco** [NativeScript/nativescript-fresco#4]
When I am navigating back to a page that contains a listview with fresco handling images I get this error.

```
com.tns.NativeScriptException: 
Calling js method onHiddenChanged failed

TypeError: Cannot read property 'setImageURI' of undefined
File: "/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/nativescript-fresco/fresco/fresco.js, line: 19, column: 21

StackTrace: 
Frame: function:'FrescoDrawee._clearAndroidReference', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/nativescript-fresco/fresco/fresco.js', line: 19, column: 22
Frame: function:'View._onDetached', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 191, column: 14
Frame: function:'eachChild', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 185, column: 23
Frame: function:'LayoutBase._eachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/layouts/layout-base.js', line: 139, column: 22
Frame: function:'View._onDetached', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 188, column: 18
Frame: function:'eachChild', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 185, column: 23
Frame: function:'LayoutBase._eachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/layouts/layout-base.js', line: 139, column: 22
Frame: function:'View._onDetached', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 188, column: 18
Frame: function:'View._removeViewCore', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 150, column: 14
Frame: function:'View._removeView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 948, column: 14
Frame: function:'LayoutBase.removeChild', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/layouts/layout-base.js', line: 52, column: 14
Frame: function:'LayoutBase.removeChildren', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/layouts/layout-base.js', line: 59, column: 18
Frame: function:'Repeater.refresh', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/repeater/repeater.js', line: 96, column: 30
Frame: function:'Repeater.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/repeater/repeater.js', line: 82, column: 18
Frame: function:'eachChild', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 606, column: 23
Frame: function:'LayoutBase._eachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/layouts/layout-base.js', line: 139, column: 22
Frame: function:'View._loadEachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 609, column: 18
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 599, column: 14
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 102, column: 35
Frame: function:'eachChild', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 606, column: 23
Frame: function:'LayoutBase._eachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/layouts/layout-base.js', line: 139, column: 22
Frame: function:'View._loadEachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 609, column: 18
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 599, column: 14
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 102, column: 35
Frame: function:'eachChild', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 606, column: 23
Frame: function:'ContentView._eachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
Frame: function:'View._loadEachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 609, column: 18
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 599, column: 14
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 102, column: 35
Frame: function:'ScrollView.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/scroll-view/scroll-view-common.js', line: 40, column: 35
Frame: function:'eachChild', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 606, column: 23
Frame: function:'TabView._eachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/tab-view/tab-view-common.js', line: 237, column: 26
Frame: function:'View._loadEachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 609, column: 18
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 599, column: 14
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 102, column: 35
Frame: function:'eachChild', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 606, column: 23
Frame: function:'ContentView._eachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
Frame: function:'Page._eachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/page/page-common.js', line: 246, column: 41
Frame: function:'View._loadEachChildView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 609, column: 18
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 599, column: 14
Frame: function:'View.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 102, column: 35
Frame: function:'Page.onLoaded', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/page/page-common.js', line: 44, column: 35
Frame: function:'View._addViewCore', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 924, column: 18
Frame: function:'View._addViewCore', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view.js', line: 146, column: 39
Frame: function:'View._addView', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/core/view-common.js', line: 912, column: 14
Frame: function:'onFragmentShown', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/frame/frame.js', line: 124, column: 11
Frame: function:'android.app.Fragment.extend.onHiddenChanged', file:'/data/data/com.smarpsocial.smarpshare/files/app/tns_modules/ui/frame/frame.js', line: 71, column: 17

at com.tns.Platform.callJSMethodNative(Native Method)
at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
at com.tns.Platform.callJSMethod(Platform.java:711)
at com.tns.Platform.callJSMethod(Platform.java:690)
at com.tns.Platform.callJSMethod(Platform.java:680)
at com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l34_c42__.onHiddenChanged(android.app.Fragment.java)
at android.app.FragmentManagerImpl.showFragment(FragmentManager.java:1308)
at android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:1636)
at android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1639)
at android.app.FragmentManagerImpl$3.run(FragmentManager.java:585)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by VladimirAmiorkov** [comment]
The issue is not longer reproducible in the latest 1.0.0 version.
