### ISSUE TITLE
Cannot read property 'imagepipeline' of undefined File: "<unknown>, line: 1, column: 265

### ISSUE THREAD

**Issue by ryc16** [NativeScript/nativescript-fresco#8]
Can't get the app startup.

```
Platform: Windows
>tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.1.0           │ 2.1.0          │ Up to date    │
│ tns-core-modules │ 2.1.0           │ 2.1.0          │ Up to date    │
│ tns-android      │ 2.1.1           │ 2.1.1          │ Up to date    │
│ tns-ios          │                 │ 2.1.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

Steps:

> tns create demo-fresco
> cd demo-fresco
> tns platform add android
> tns plugin add nativescript-fresco

After adding below and run /> tns livesync android --watch got below exception.

```
var application = require("application");
var fresco = require("nativescript-fresco");

if (application.android) {
    application.onLaunch = function (intent) {
        fresco.initialize();
    };
}
```

ERROR

```

--------- beginning of /dev/log/main
D/AndroidRuntime( 5636):
D/AndroidRuntime( 5636): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 5636): CheckJNI is OFF
D/dalvikvm( 5636): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 5636): Added shared lib libjavacore.so 0x0
D/dalvikvm( 5636): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 5636): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 5636): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
D/dalvikvm( 5636): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/cutils-trace( 5636): Error opening trace file: No such file or directory (2)
E/memtrack( 5636): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 5636): failed to load memtrack module: -2
D/AndroidRuntime( 5636): Calling main entry com.android.commands.pm.Pm
D/AndroidRuntime( 5636): Shutting down VM
D/dalvikvm( 5636): GC_CONCURRENT freed 241K, 31% free 558K/804K, paused 0ms+0ms, total 1ms
D/AndroidRuntime( 5655):
D/AndroidRuntime( 5655): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 5655): CheckJNI is OFF
D/dalvikvm( 5655): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 5655): Added shared lib libjavacore.so 0x0
D/dalvikvm( 5655): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 5655): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 5655): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 5655): Error opening trace file: No such file or directory (2)
D/dalvikvm( 5655): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack( 5655): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 5655): failed to load memtrack module: -2
D/AndroidRuntime( 5655): Calling main entry com.android.commands.am.Am
--------- beginning of /dev/log/system
I/ActivityManager(  808): Force stopping org.nativescript.demofresco appid=10068 user=0: from pid 5655
I/ActivityManager(  808): Killing 5605:org.nativescript.demofresco/u0a68 (adj 0): stop org.nativescript.demofresco
W/ActivityManager(  808): Force removing ActivityRecord{529da1c4 u0 org.nativescript.demofresco/com.tns.ErrorReportActivity t54}: app died, no saved state
W/InputDispatcher(  808): channel '52ad734c org.nativescript.demofresco/com.tns.ErrorReportActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  808): channel '52ad734c org.nativescript.demofresco/com.tns.ErrorReportActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  808): Attempted to unregister already unregistered input channel '52ad734c org.nativescript.demofresco/com.tns.ErrorReportActivity (server)'
I/WindowState(  808): WIN DEATH: Window{52ad734c u0 org.nativescript.demofresco/com.tns.ErrorReportActivity}
D/AndroidRuntime( 5655): Shutting down VM
D/dalvikvm( 5655): GC_CONCURRENT freed 92K, 15% free 544K/640K, paused 0ms+0ms, total 1ms
W/EGL_xap ( 5132): eglSurfaceAttrib not implemented
W/Binder  ( 1037): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 1037): java.lang.NullPointerException
W/Binder  ( 1037):      at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  ( 1037):      at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  ( 1037):      at android.os.Binder.execTransact(Binder.java:404)
W/Binder  ( 1037):      at dalvik.system.NativeStart.run(Native Method)
W/InputMethodManagerService(  808): Got RemoteException sending setActive(false) notification to pid 5605 uid 10068
D/AndroidRuntime( 5667):
D/AndroidRuntime( 5667): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 5667): CheckJNI is OFF
D/dalvikvm( 5667): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 5667): Added shared lib libjavacore.so 0x0
D/dalvikvm( 5667): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 5667): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 5667): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 5667): Error opening trace file: No such file or directory (2)
D/dalvikvm( 5667): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack( 5667): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 5667): failed to load memtrack module: -2
D/AndroidRuntime( 5667): Calling main entry com.android.commands.am.Am
I/ActivityManager(  808): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=org.nativescript.demofresco/com.tns.NativeScriptActivity} from pid 5667
D/dalvikvm(  808): GC_FOR_ALLOC freed 555K, 22% free 9360K/11976K, paused 10ms, total 10ms
D/dalvikvm(  808): GC_FOR_ALLOC freed 428K, 23% free 9309K/11976K, paused 11ms, total 11ms
D/AndroidRuntime( 5667): Shutting down VM
D/dalvikvm( 5667): GC_CONCURRENT freed 94K, 15% free 576K/676K, paused 0ms+0ms, total 1ms
D/dalvikvm( 5678): Late-enabling CheckJNI
I/ActivityManager(  808): Start proc org.nativescript.demofresco for activity org.nativescript.demofresco/com.tns.NativeScriptActivity: pid=5678 uid=10068 gids={50068, 1028, 1015, 3003}
D/dalvikvm( 5678): Trying to load lib /data/app-lib/org.nativescript.demofresco-1/libNativeScript.so 0xa5073b88
D/dalvikvm( 5678): Added shared lib /data/app-lib/org.nativescript.demofresco-1/libNativeScript.so 0xa5073b88
I/TNS.Native( 5678): NativeScript Runtime Version 2.1.1, commit bce725184f249812c73163957aa50aa9339edddb
D/TNS.Native( 5678): JNI_ONLoad
D/TNS.Native( 5678): JNI_ONLoad END
D/dalvikvm( 5678): GC_CONCURRENT freed 281K, 12% free 2941K/3336K, paused 2ms+0ms, total 4ms
D/TNS.Native( 5678): V8 version 4.7.80
D/TNS.Native( 5678): lenNodes=57624, lenNames=655053, lenValues=728804
D/TNS.Native( 5678): time=1
D/TNS.Java( 5678): Enabling NativeScript Debugger Agent
D/dalvikvm( 5678): GC_CONCURRENT freed 295K, 12% free 3034K/3440K, paused 2ms+1ms, total 8ms
D/AndroidRuntime( 5678): Shutting down VM
W/dalvikvm( 5678): threadid=1: thread exiting with uncaught exception (group=0xa4d92b20)
W/System.err( 5678): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
W/System.err( 5678): Fail to load module: /data/data/org.nativescript.demofresco/files/app/app.js
W/System.err( 5678): TypeError: Cannot read property 'imagepipeline' of undefined
W/System.err( 5678): File: "<unknown>, line: 1, column: 265
W/System.err( 5678): StackTrace:
W/System.err( 5678):    Frame: function:'', file:'/data/data/org.nativescript.demofresco/files/app/tns_modules/nativescript-fresco/nativescript-fresco.js', line: 35, column: 15
W/System.err( 5678):    Frame: function:'require', file:'', line: 1, column: 266
W/System.err( 5678):    Frame: function:'', file:'/data/data/org.nativescript.demofresco/files/app/app.js', line: 2, column: 14
W/System.err( 5678):    Frame: function:'require', file:'', line: 1, column: 266
W/System.err( 5678):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4347)
W/System.err( 5678):    at android.app.ActivityThread.access$1500(ActivityThread.java:135)
W/System.err( 5678):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
W/System.err( 5678):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 5678):    at android.os.Looper.loop(Looper.java:136)
W/System.err( 5678):    at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err( 5678):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 5678):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 5678):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err( 5678):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err( 5678):    at dalvik.system.NativeStart.main(Native Method)
W/System.err( 5678): Caused by: com.tns.NativeScriptException:
W/System.err( 5678): Fail to load module: /data/data/org.nativescript.demofresco/files/app/app.js
W/System.err( 5678): TypeError: Cannot read property 'imagepipeline' of undefined
W/System.err( 5678): File: "<unknown>, line: 1, column: 265
W/System.err( 5678): StackTrace:
W/System.err( 5678):    Frame: function:'', file:'/data/data/org.nativescript.demofresco/files/app/tns_modules/nativescript-fresco/nativescript-fresco.js', line: 35, column: 15
W/System.err( 5678):    Frame: function:'require', file:'', line: 1, column: 266
W/System.err( 5678):    Frame: function:'', file:'/data/data/org.nativescript.demofresco/files/app/app.js', line: 2, column: 14
W/System.err( 5678):    Frame: function:'require', file:'', line: 1, column: 266
W/System.err( 5678):    at com.tns.Runtime.runModule(Native Method)
W/System.err( 5678):    at com.tns.Runtime.runModule(Runtime.java:241)
W/System.err( 5678):    at com.tns.Runtime.run(Runtime.java:235)
W/System.err( 5678):    at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
W/System.err( 5678):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
W/System.err( 5678):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
W/System.err( 5678):    ... 10 more
I/ActivityManager(  808): START u0 {flg=0x14008000 cmp=org.nativescript.demofresco/com.tns.ErrorReportActivity (has extras)} from pid -1
D/dalvikvm(  808): GC_FOR_ALLOC freed 399K, 23% free 9320K/11976K, paused 9ms, total 9ms
D/dalvikvm(  808): GC_FOR_ALLOC freed 378K, 23% free 9317K/11976K, paused 15ms, total 15ms
I/Process ( 5678): Sending signal. PID: 5678 SIG: 9
I/ActivityManager(  808): Process org.nativescript.demofresco (pid 5678) has died.
D/dalvikvm( 5702): Late-enabling CheckJNI
I/ActivityManager(  808): Start proc org.nativescript.demofresco for activity org.nativescript.demofresco/com.tns.ErrorReportActivity: pid=5702 uid=10068 gids={50068, 1028, 1015, 3003}
D/dalvikvm( 5702): Trying to load lib /data/app-lib/org.nativescript.demofresco-1/libNativeScript.so 0xa50749d8
D/dalvikvm( 5702): Added shared lib /data/app-lib/org.nativescript.demofresco-1/libNativeScript.so 0xa50749d8
I/TNS.Native( 5702): NativeScript Runtime Version 2.1.1, commit bce725184f249812c73163957aa50aa9339edddb
D/TNS.Native( 5702): JNI_ONLoad
D/TNS.Native( 5702): JNI_ONLoad END
D/libEGL  ( 5702): loaded /system/lib/egl/libEGL_xap.so
D/eglCodecCommon( 5702): TcpStream::connect() - management hostname is 10.71.34.101
D/eglCodecCommon( 5702): TcpStream::connect() - connecting host: 10.71.34.1
D/        ( 5702): HostConnection::get() New Host Connection established 0xb88d15f0, tid 5702
D/libEGL  ( 5702): loaded /system/lib/egl/libGLESv1_CM_xap.so
D/libEGL  ( 5702): loaded /system/lib/egl/libGLESv2_xap.so
W/EGL_xap ( 5702): eglSurfaceAttrib not implemented
E/OpenGLRenderer( 5702): Getting MAX_TEXTURE_SIZE from GradienCache
E/OpenGLRenderer( 5702): MAX_TEXTURE_SIZE: 8192
E/OpenGLRenderer( 5702): Getting MAX_TEXTURE_SIZE from Caches::initConstraints()
E/OpenGLRenderer( 5702): MAX_TEXTURE_SIZE: 8192
D/OpenGLRenderer( 5702): Enabling debug mode 0
I/ActivityManager(  808): Displayed org.nativescript.demofresco/com.tns.ErrorReportActivity: +600ms (total +1s557ms)

```

Any idea? How to resolve this?

**Comment by VladimirAmiorkov** [comment]
Hi @ryc16 ,

I tested the described scenario with a fresh {N} project and I was not able to observe the described error. The project ran as expected after doing tns livesync android --watch and also tried adding an FrescoDrawee:

<nativescript-fresco:FrescoDrawee imageUri="https://docs.nativescript.org/angular/img/cli-getting-started/angular/chapter0/NativeScript_logo.png" width="300" height="300"/>

which again worked as expected and showed the image. Here is the full code of my test app:

app.js:

```
var application = require("application");
var fresco = require("nativescript-fresco");

if (application.android) {
    application.onLaunch = function (intent) {
        fresco.initialize();
    };
}
```

application.start({ moduleName: "main-page" });

and the main-page.xml:

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="onNavigatingTo" xmlns:nativescript-fresco="nativescript-fresco">
  <StackLayout>
    <Label text="Tap the button" class="title"/>
    <Button text="TAP" tap="{{ onTap }}" />
    <Label text="{{ message }}" class="message" textWrap="true"/>
    <nativescript-fresco:FrescoDrawee imageUri="https://docs.nativescript.org/angular/img/cli-getting-started/angular/chapter0/NativeScript_logo.png" width="300" height="300"/>
  </StackLayout>
</Page>
```

**Comment by VladimirAmiorkov** [comment]
Closing this issue for now. if you still observe it please reopen it with additional information.
